version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/application.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: cups

images:
  - id: cups
    target: service
    service: cups
    source: docker.io/hanxi/cups-web
    channel: stable
    tag_regex: '^v\d+\.\d+\.\d+$'
    version_regex: '^v(?P<version>\d+\.\d+\.\d+)$'
    version_template: '{version}'
    delivery:
      mode: lazycat

stores:
  official:
    enabled: true
    continue_if_newer_version: true
    skip_if_version_exists: true
    retry:
      enabled: false
  private:
    enabled: false
    skip_if_version_exists: false
